site_name: Minium Core
pages:
  - ['index.md', 'Introduction']
  - ['third-parties.md']
  - ['changelog.md']
  - ['tools/minium-developer.md', 'Tools']
  - ['tools/minium-automator.md', 'Tools']
site_dir: '${static.docs.dir}'
theme: ''
theme_dir: 'readthedocs-minium'

